version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  curateNews:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            echo $SENDGRID_API_KEY
            pipenv run python news.py
          
          name: news

workflows:
  version: 2.1
  nightly:
    triggers:
      - schedule:
          cron: "34 22 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - curateNews

